### ISSUE TITLE
Daily update emails don't... update?

### ISSUE THREAD

**Issue by lowercasename** [lowercasename/sweet#165] opened 2019-09-16 17:13 UTC
So this is an odd one I've been watching for a while. Over the last couple of days, my daily update email came each day, but it had the same three notifications in it - ones I'd seen the first time. It looks maybe like, if you're getting the email sent, but there aren't actually any new notifications for it to pick up, it'll just send the last set it has available?? As soon as there are new notifications, it stops sending the old set.

Is it only me getting this?

**Comment by toBeOfUse** [comment] 2019-09-16 22:29
I love bugs that take multiple days to reproduce in their original forms

**Comment by toBeOfUse** [comment] 2019-09-16 22:31
I do think I noticed an email for my alt account's notifications that contained the same three notifications as the previous email had even though I'd gone and marked them read since

**Comment by toBeOfUse** [comment] 2019-09-16 22:42
This one should be another easy fix though, it looks like the emailer just keeps using the same user document that's fetched from the database at server boot-up without ever, like, checking to see if the user's notifications have changed since then

**Comment by toBeOfUse** [comment] 2019-09-17 00:28
Fixed in 1050640, probably

**Closed** 2020-02-11 22:55 UTC
